apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-consul-deployment
spec:
  selector:
    matchLabels:
      app: happy-consul
  replicas: 1
  template:
    metadata:
      labels:
        app: happy-consul
    spec:
      containers:
        - name: happy-consul
          image: consul:latest
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          args:
            - "agent"
            - "-dev"
          ports:
            - containerPort: 8500
              name: "ui"
---
apiVersion: apps/v1
kind: Service
metadata:
  name: happy-consul #Service 的名称
  labels: #Service 自己的标签
    app: happy-consul #为该 Service 设置 key 为 app，value 为 nginx 的标签
spec: #这是关于该 Service 的定义，描述了 Service 如何选择 Pod，如何被访问
  selector: #标签选择器
    app: happy-consul #选择包含标签 app:nginx 的 Pod
  ports:
    - name: happy-consul-srv-port #端口的名字
      protocol: TCP #协议类型 TCP/UDP
      port: 30002 #集群内的其他容器组可通过 80 端口访问 Service
      nodePort: 30002 #通过任意节点的 32600 端口访问 Service
      targetPort: 8500 #将请求转发到匹配 Pod 的端口
  type: NodePort #Serive的类型，ClusterIP/NodePort/LoaderBalancer
