name: k8s

on: push

jobs:
  deploy:
    name: k8s-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: k3s-apply-config
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f ./config.yaml
          #args: get nodes
